### ISSUE TITLE
Review by MazeSolver

### ISSUE THREAD

**Issue by ColderWinters** [vchi90/MeowMaze#3]
Your recursive abstraction is incredibly unclear. Using the idea of backtracking inside of the recursive abstraction is incredibly unclear, as well as involves recursive language. Moreover, the recursive abstraction should be expansive in naturn, it splits the problem into smaller problems, but "marking a tile for backtracking" seems like something relavent to the collapse of the problem, not the branching of it. The issue as I see it is in essence that you made the recursive abstraction regard the collapse of the problem rather than the expansion of it, leaving the expansion unclear.

**Comment by vchi90** [comment]
Thanks for your feedback! Reworked the wording, if unsatisfied, please reopen this issue.
